networks:
  hack: {}

services:
  db-init:
    build:
      context: .
      dockerfile: Dockerfile.init-db
    networks:
      - hack
    depends_on:
      - postgres

  postgres:
    image: postgres:16.1
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      INITIALIZE_DB: 'true'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:delegated
      - ./db:/db:delegated
    ports:
      - 5432:5432
    networks:
      - hack
    container_name: postgres

