FROM node:23-alpine AS pnpm
ARG PNPM_VERSION=8.10.0
RUN npm install -g pnpm@${PNPM_VERSION}

COPY ./prisma ./prisma
COPY .env.docker .env
COPY ./init-db ./init-db

CMD [ "node", "init-db/init-db.js" ]